//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoarUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoarUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code,Region
        ///201,NJ
        ///202,DC
        ///203,CT
        ///204,MB
        ///205,AL
        ///206,WA
        ///207,ME
        ///208,ID
        ///209,CA
        ///210,TX
        ///212,NY
        ///213,CA
        ///214,TX
        ///215,PA
        ///216,OH
        ///217,IL
        ///218,MN
        ///219,IN
        ///224,IL
        ///225,LA
        ///226,ON
        ///228,MS
        ///229,GA
        ///231,MI
        ///234,OH
        ///239,FL
        ///240,MD
        ///242,Bahamas
        ///246,Barbados
        ///248,MI
        ///250,BC
        ///251,AL
        ///252,NC
        ///253,WA
        ///254,TX
        ///256,AL
        ///260,IN
        ///262,WI
        ///264,Anguilla
        ///267,PA
        ///268,Antigua and Barbuda
        ///269,MI
        ///270,KY
        ///276,VA
        ///281,TX
        ///284,British Virgin Islands
        ///289,ON
        ///301,MD
        ///302,DE
        ///303,CO
        ///304,WV
        ///305,FL
        ///306,SK
        ///307,WY
        ///308,NE
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string area_codes {
            get {
                return ResourceManager.GetString("area_codes", resourceCulture);
            }
        }
    }
}
